
language: python
python:
 - "2.7"
install:
 - pip install -r requirements.txt
 - pip install coveralls
services:
 - postgresql
before_script:
 - psql -c "CREATE DATABASE politico_test_db;" -U postgres
 - psql -c "CREATE USER christine WITH PASSWORD '1234567';" -U postgres
env:
 -  Test_Database="postgres://christine:1234567@localhost/politico_test"
script:
 - python -m pytest --cov=app tests/
after_success:
 - coveralls